stripped out lines no longer needed

diff --git a/bin/update_repo_as_needed b/bin/update_repo_as_needed
--- a/bin/update_repo_as_needed
+++ b/bin/update_repo_as_needed
@@ -2,55 +2,12 @@
 function log(){
     echo "`date` - ${1}"
 }
-################################################################################
-#
-# can be used to check and update (as needed) a git repository
-# if invoked with no parameters the current directory will be checked and, if
-# it's a git repo with remote changes available, updated
-#
-# usage:
-#   update_repo_as_needed [directory]
-#
-################################################################################
-ACTION=$1
-case $ACTION in
-    '-h')
-        ACTION=help
-        ;;
-    '--help')
-        ACTION=help
-        ;;
-    *)
-        # don't know what it is, must be trying to give us a dir
-        REPO_DIR=$ACTION
-        # currently this action triggers nothing explicitly this is
-        # only here because I suck
-        ACTION=update
-        ;;
-esac
 
-if [ $ACTION == "help" ]; then
-    echo "`basename $0` [directory]"
-    echo "    directory - optional repository directory to check, if not "
-    echo "       provided the current directory is checked"
-    echo ""
-    echo "Actions:"
-    echo "    If the repo dir contains a file named update_repo_action which is"
-    echo "      executable, that file will be executed after an update of the "
-    echo "      contents of the repo dir.  That is: if new code is retrieved and an"
-    echo "      executeable file 'update_repo_action' exists in the root of the repo"
-    echo "      it will be executed."
-    exit 1
-fi
-
-if [ "${REPO_DIR}x" == "x" ]; then
-    # no dir provided, assume current directory
-    REPO_DIR=`pwd`
-else
-    #if you specify a directory, it had better exist
-    if [ ! -d "${REPO_DIR}" ]; then
-      exit 1
-    fi
+REPO_DIR=$1
+#if you specify a directory, it had better exist
+if [ ! -d "${REPO_DIR}" ]; then
+  log "${REPO_DIR} doesn't exist"
+  exit 1
 fi
 
 cd ${REPO_DIR}
@@ -65,8 +22,8 @@ fi
 
 FETCH_RESULTS=`git fetch --all `
 if [ $? -ne 0 ]; then
-    echo "fetch error"
-    echo $FETCH_RESULTS
+    log "fetch error in ${REPO_DIR}"
+    log $FETCH_RESULTS
     exit 4
 fi
 CURRENT_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
